name: pylint errors
on:
  push:
    branches:
      - main
jobs:
  run-python-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install pylint
        run: pip install pylint
      - name: Run python
        run: python final.py
      - name: Fail if there are pylint errors
        if: ${{ steps.run-pylint.outputs.violations-found > 0 }}
        run: exit 1
